insert into customer.details (id, customer_name, joined_on,borrowed_book_id) values (1, 'Shurlocke Laird-Craig', '12/8/2022',1);
insert into customer.details (id, customer_name, joined_on, borrowed_book_id) values (2, 'Verina Seale', '1/4/2023', 3);
insert into customer.details (id, customer_name, joined_on, borrowed_book_id) values (3, 'Brynn Gerge', '7/12/2023', null);
insert into customer.details (id, customer_name, joined_on, borrowed_book_id) values (4, 'Jordain Eykelbosch', '1/3/2023', null);
insert into customer.details (id, customer_name, joined_on, borrowed_book_id) values (5, 'Tierney Coursor', '10/12/2022', 2);
insert into customer.details (id, customer_name, joined_on, borrowed_book_id) values (6, 'Helena Shaw', '12/4/2022', null);
insert into customer.details (id, customer_name, joined_on, borrowed_book_id) values (7, 'Merry Mark', '6/1/2023', null);
insert into customer.details (id, customer_name, joined_on, borrowed_book_id) values (8, 'Marcela Dewsbury', '10/19/2022', null);
insert into customer.details (id, customer_name, joined_on, borrowed_book_id) values (9, 'Rivkah O''Scanlon', '7/1/2023', null);
insert into customer.details (id, customer_name, joined_on, borrowed_book_id) values (10, 'Carola Jillett', '1/25/2023', null);